const sharp = require("sharp");

// Matrix generated by bwip-js 4.11.4 (Data Matrix ECC200, FNC1/GS1 mode)
// for the exact fixture payload. The pixels are kept here so tests do not
// require a production encoder or network access.
// bwipjs.raw({ bcid: "datamatrix", parsefnc: true,
//   text: "^FNC10104680036912629215JuVJmTnOR:3H\x1D93kjJw" })[0]
// ZXing exposes the leading FNC1 as ASCII 29 too; preserve that byte.
const MATRIX = [
  "1010101010101010101010", "1101100000111100111011", "1000101101100101111000",
  "1011000011101011111101", "1110010001011101101010", "1010000011010101001011",
  "1111011001101000011100", "1111011010101001110111", "1010100111111100010100",
  "1101110100100011100001", "1011010000011000111110", "1111010010110000001001",
  "1100011101001001001110", "1011101011100000110101", "1001110111010111101100",
  "1101110010000111111101", "1000110010111100010010", "1001110000010101010101",
  "1011111111100110001100", "1110100100110100111011", "1010000000110000100110",
  "1111111111111111111111",
];

async function dataMatrixPng({ scale = 10, quiet = 2 } = {}) {
  const size = MATRIX.length + quiet * 2;
  const pixels = Buffer.alloc(size * size);
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
    const dark = y >= quiet && y < quiet + MATRIX.length && x >= quiet && x < quiet + MATRIX.length
      ? MATRIX[y - quiet][x - quiet] === "1" : false;
    pixels[y * size + x] = dark ? 0 : 255;
  }
  return sharp(pixels, { raw: { width: size, height: size, channels: 1 } })
    .resize(size * scale, size * scale, { kernel: "nearest" }).png().toBuffer();
}

module.exports = { dataMatrixPng };
